export const nflLogoMap = {
  "49ers": "/assets/nfl-logos/49ers.png",
  Bears: "/assets/nfl-logos/bears.png",
  Bengals: "/assets/nfl-logos/bengals.png",
  Bills: "/assets/nfl-logos/bills.png",
  Broncos: "/assets/nfl-logos/broncos.png",
  Browns: "/assets/nfl-logos/browns.png",
  Buccaneers: "/assets/nfl-logos/buccaneers.png",
  Cardinals: "/assets/nfl-logos/cardinals.png",
  Chargers: "/assets/nfl-logos/chargers.png",
  Chiefs: "/assets/nfl-logos/chiefs.png",
  Colts: "/assets/nfl-logos/colts.png",
  Cowboys: "/assets/nfl-logos/cowboys.png",
  Dolphins: "/assets/nfl-logos/dolphins.png",
  Eagles: "/assets/nfl-logos/eagles.png",
  Falcons: "/assets/nfl-logos/falcons.png",
  Giants: "/assets/nfl-logos/giants.png",
  Jaguars: "/assets/nfl-logos/jaguars.png",
  Jets: "/assets/nfl-logos/jets.png",
  Lions: "/assets/nfl-logos/lions.png",
  Packers: "/assets/nfl-logos/packers.png",
  Panthers: "/assets/nfl-logos/panthers.png",
  Patriots: "/assets/nfl-logos/patriots.png",
  Raiders: "/assets/nfl-logos/raiders.png",
  Rams: "/assets/nfl-logos/rams.png",
  Ravens: "/assets/nfl-logos/ravens.png",
  Saints: "/assets/nfl-logos/saints.png",
  Seahawks: "/assets/nfl-logos/seahawks.png",
  Steelers: "/assets/nfl-logos/steelers.png",
  Texans: "/assets/nfl-logos/texans.png",
  Titans: "/assets/nfl-logos/titans.png",
  Vikings: "/assets/nfl-logos/vikings.png",
  Commanders: "/assets/nfl-logos/redskins.png",
  Redskins: "/assets/nfl-logos/redskins.png",
  NFL: "/assets/nfl-logos/_NFL_logo.png",
};

export const nbaLogoMap = {
  "76ers": "/assets/nba-logos/76ers.png",
  Bucks: "/assets/nba-logos/bucks.png",
  Bulls: "/assets/nba-logos/bulls.png",
  Cavaliers: "/assets/nba-logos/cavaliers.png",
  Celtics: "/assets/nba-logos/celtics.png",
  Clippers: "/assets/nba-logos/clippers.png",
  Grizzlies: "/assets/nba-logos/grizzlies.png",
  Hawks: "/assets/nba-logos/hawks.png",
  Heat: "/assets/nba-logos/heat.png",
  Hornets: "/assets/nba-logos/hornets.png",
  Jazz: "/assets/nba-logos/jazz.png",
  Kings: "/assets/nba-logos/kings.png",
  Knicks: "/assets/nba-logos/knicks.png",
  Lakers: "/assets/nba-logos/lakers.png",
  Magic: "/assets/nba-logos/magic.png",
  Mavericks: "/assets/nba-logos/mavericks.png",
  Nets: "/assets/nba-logos/nets.png",
  Nuggets: "/assets/nba-logos/nuggets.png",
  Pacers: "/assets/nba-logos/pacers.png",
  Pelicans: "/assets/nba-logos/pelicans.png",
  Pistons: "/assets/nba-logos/pistons.png",
  Raptors: "/assets/nba-logos/raptors.png",
  Rockets: "/assets/nba-logos/rockets.png",
  Spurs: "/assets/nba-logos/spurs.png",
  Suns: "/assets/nba-logos/suns.png",
  Thunder: "/assets/nba-logos/thunder.png",
  Timberwolves: "/assets/nba-logos/timberwolves.png",
  "Trail Blazers": "/assets/nba-logos/trailBlazers.png",
  Warriors: "/assets/nba-logos/warriors.png",
  Wizards: "/assets/nba-logos/wizards.png",
  NBA: "/assets/nba-logos/_NBA_logo.png",
};

export const mlbLogoMap = {
  Angels: "/assets/mlb-logos/angels.png",
  Astros: "/assets/mlb-logos/astros.png",
  Athletics: "/assets/mlb-logos/athletics.png",
  "Blue Jays": "/assets/mlb-logos/blueJays.png",
  Braves: "/assets/mlb-logos/braves.png",
  Brewers: "/assets/mlb-logos/brewers.png",
  Cardinals: "/assets/mlb-logos/cardinals.png",
  Cubs: "/assets/mlb-logos/cubs.png",
  Diamondbacks: "/assets/mlb-logos/diamondbacks.png",
  Dodgers: "/assets/mlb-logos/dodgers.png",
  Giants: "/assets/mlb-logos/giants.png",
  Guardians: "/assets/mlb-logos/indians.png",
  Mariners: "/assets/mlb-logos/mariners.png",
  Marlins: "/assets/mlb-logos/marlins.png",
  Mets: "/assets/mlb-logos/mets.png",
  Nationals: "/assets/mlb-logos/nationals.png",
  Orioles: "/assets/mlb-logos/orioles.png",
  Padres: "/assets/mlb-logos/padres.png",
  Phillies: "/assets/mlb-logos/phillies.png",
  Pirates: "/assets/mlb-logos/pirates.png",
  Rangers: "/assets/mlb-logos/rangers.png",
  Rays: "/assets/mlb-logos/rays.png",
  "Red Sox": "/assets/mlb-logos/redSox.png",
  Reds: "/assets/mlb-logos/reds.png",
  Rockies: "/assets/mlb-logos/rockies.png",
  Royals: "/assets/mlb-logos/royals.png",
  Tigers: "/assets/mlb-logos/tigers.png",
  Twins: "/assets/mlb-logos/twins.png",
  "White Sox": "/assets/mlb-logos/whiteSox.png",
  Yankees: "/assets/mlb-logos/yankees.png",
  MLB: "/assets/mlb-logos/_MLB_logo.png",
};

export default { nflLogoMap, nbaLogoMap, mlbLogoMap };
