export const nflLogoMap = {
  "49ers": "/assets/nfl-logos/49ers.svg",
  Bears: "/assets/nfl-logos/bears.svg",
  Bengals: "/assets/nfl-logos/bengals.svg",
  Bills: "/assets/nfl-logos/bills.svg",
  Broncos: "/assets/nfl-logos/broncos.svg",
  Browns: "/assets/nfl-logos/browns.svg",
  Buccaneers: "/assets/nfl-logos/buccaneers.svg",
  Cardinals: "/assets/nfl-logos/cardinals.svg",
  Chargers: "/assets/nfl-logos/chargers.svg",
  Chiefs: "/assets/nfl-logos/chiefs.svg",
  Colts: "/assets/nfl-logos/colts.svg",
  Cowboys: "/assets/nfl-logos/cowboys.svg",
  Dolphins: "/assets/nfl-logos/dolphins.svg",
  Eagles: "/assets/nfl-logos/eagles.svg",
  Falcons: "/assets/nfl-logos/falcons.svg",
  Giants: "/assets/nfl-logos/giants.svg",
  Jaguars: "/assets/nfl-logos/jaguars.svg",
  Jets: "/assets/nfl-logos/jets.svg",
  Lions: "/assets/nfl-logos/lions.svg",
  Packers: "/assets/nfl-logos/packers.svg",
  Panthers: "/assets/nfl-logos/panthers.svg",
  Patriots: "/assets/nfl-logos/patriots.svg",
  Raiders: "/assets/nfl-logos/raiders.svg",
  Rams: "/assets/nfl-logos/rams.svg",
  Ravens: "/assets/nfl-logos/ravens.svg",
  Saints: "/assets/nfl-logos/saints.svg",
  Seahawks: "/assets/nfl-logos/seahawks.svg",
  Steelers: "/assets/nfl-logos/steelers.svg",
  Texans: "/assets/nfl-logos/texans.svg",
  Titans: "/assets/nfl-logos/titans.svg",
  Vikings: "/assets/nfl-logos/vikings.svg",
  Commanders: "/assets/nfl-logos/redskins.svg",
  Redskins: "/assets/nfl-logos/redskins.svg",
  NFL: "/assets/nfl-logos/_NFL_logo.svg",
};

export const nbaLogoMap = {
  "76ers": "/assets/nba-logos/76ers.svg",
  Bucks: "/assets/nba-logos/bucks.svg",
  Bulls: "/assets/nba-logos/bulls.svg",
  Cavaliers: "/assets/nba-logos/cavaliers.svg",
  Celtics: "/assets/nba-logos/celtics.svg",
  Clippers: "/assets/nba-logos/clippers.svg",
  Grizzlies: "/assets/nba-logos/grizzlies.svg",
  Hawks: "/assets/nba-logos/hawks.svg",
  Heat: "/assets/nba-logos/heat.svg",
  Hornets: "/assets/nba-logos/hornets.svg",
  Jazz: "/assets/nba-logos/jazz.svg",
  Kings: "/assets/nba-logos/kings.svg",
  Knicks: "/assets/nba-logos/knicks.svg",
  Lakers: "/assets/nba-logos/lakers.svg",
  Magic: "/assets/nba-logos/magic.svg",
  Mavericks: "/assets/nba-logos/mavericks.svg",
  Nets: "/assets/nba-logos/nets.svg",
  Nuggets: "/assets/nba-logos/nuggets.svg",
  Pacers: "/assets/nba-logos/pacers.svg",
  Pelicans: "/assets/nba-logos/pelicans.svg",
  Pistons: "/assets/nba-logos/pistons.svg",
  Raptors: "/assets/nba-logos/raptors.svg",
  Rockets: "/assets/nba-logos/rockets.svg",
  Spurs: "/assets/nba-logos/spurs.svg",
  Suns: "/assets/nba-logos/suns.svg",
  Thunder: "/assets/nba-logos/thunder.svg",
  Timberwolves: "/assets/nba-logos/timberwolves.svg",
  "Trail Blazers": "/assets/nba-logos/trailBlazers.svg",
  Warriors: "/assets/nba-logos/warriors.svg",
  Wizards: "/assets/nba-logos/wizards.svg",
  NBA: "/assets/nba-logos/_NBA_logo.svg",
};

export const mlbLogoMap = {
  Angels: "/assets/mlb-logos/angels.png",
  Astros: "/assets/mlb-logos/astros.png",
  Athletics: "/assets/mlb-logos/athletics.png",
  "Blue Jays": "/assets/mlb-logos/blueJays.png",
  Braves: "/assets/mlb-logos/braves.png",
  Brewers: "/assets/mlb-logos/brewers.png",
  Cardinals: "/assets/mlb-logos/cardinals.png",
  Cubs: "/assets/mlb-logos/cubs.png",
  Diamondbacks: "/assets/mlb-logos/diamondbacks.png",
  Dodgers: "/assets/mlb-logos/dodgers.png",
  Giants: "/assets/mlb-logos/giants.png",
  Guardians: "/assets/mlb-logos/indians.png",
  Mariners: "/assets/mlb-logos/mariners.png",
  Marlins: "/assets/mlb-logos/marlins.png",
  Mets: "/assets/mlb-logos/mets.png",
  Nationals: "/assets/mlb-logos/nationals.png",
  Orioles: "/assets/mlb-logos/orioles.png",
  Padres: "/assets/mlb-logos/padres.png",
  Phillies: "/assets/mlb-logos/phillies.png",
  Pirates: "/assets/mlb-logos/pirates.png",
  Rangers: "/assets/mlb-logos/rangers.png",
  Rays: "/assets/mlb-logos/rays.png",
  "Red Sox": "/assets/mlb-logos/redSox.png",
  Reds: "/assets/mlb-logos/reds.png",
  Rockies: "/assets/mlb-logos/rockies.png",
  Royals: "/assets/mlb-logos/royals.png",
  Tigers: "/assets/mlb-logos/tigers.png",
  Twins: "/assets/mlb-logos/twins.png",
  "White Sox": "/assets/mlb-logos/whiteSox.png",
  Yankees: "/assets/mlb-logos/yankees.png",
  MLB: "/assets/mlb-logos/_MLB_logo.png",
};

export default { nflLogoMap, nbaLogoMap, mlbLogoMap };
